export const ATTR_MAP = {
    placeholder: 11,
    name: 11,
    vtype: 11,
    value: 10,
    datetime: 10,
    label: 10,
    alt: 10,
    for: 10,
    form: 10,
    href: 10,
    src: 10,
    autoplay: 10,
    preload: 10,
    controls: 10,
    media: 10,
    autofocus: 10,
    action: 10,
    colspan: 10,
    rowspan: 10,
    cols: 10,
    rows: 10,
    maxlength: 10,
    minlength: 10,
    max: 10,
    min: 10,
    accept: 10,
    wrap: 10,
    icon: 10,
    dirname: 10,
    dir: 10,
    cite: 10,
    multiple: 10,
    shape: 10,
    sizes: 10,
    cellpadding: 10,
    cellspacing: 10,
    formaction: 10,
    formenctype: 10,
    formmethod: 10,
    formnovalidate: 10,
    formtarget: 10,
    enctype: 10,
    method: 10,
    novalidate: 10,
    srclang: 10,
    frameborder: 10,
    noresize: 10,
    scrolling: 10,
    longdesc: 10,
    align: 10,
    sandbox: 10,
    seamless: 10,
    loading: 10,
    list: 10,
    pattern: 10,
    step: 10,
    referrerpolicy: 10,
    rel: 10,
    default: 10,
    open: 10,
    radiogroup: 10,
    compact: 10,
    reversed: 10,
    start: 10,
    border: 10,
    rules: 10,
    char: 10,
    charoff: 10,
    valign: 10,
    abbr: 10,
    axis: 10,
    headers: 10,
    scope: 10,
    nowrap: 10,
    pubdate: 10,
    lang: 10,
    kind: 10,
    loop: 10,
    muted: 10,
    type: 9,
    checked: 9,
    target: 8,
    autocomplete: 8,
    required: 8,
    readonly: 8,
    disabled: 8  // 可能没有值看下怎么处理
}

export const EXCLUDE_CLASS = ['icon-comp-win-error', 'sfv-datepicker-range-end']

export const EXCLUDE_CLASS_MODIFY = ['-hover', 'active']

export const ATTR_ARRAY = Object.keys(ATTR_MAP)
